#!/bin/bash

echo "Installing pmanh"

if [ $EUID -ne 0 ]; then
	## For 'non root' user

	### Move app directory to lib user directory
	sudo cp -r ./../pacman-helper /usr/lib

	### Create symbolic lync into bin directory
	sudo ln -s /usr/lib/pacman-helper/pmanh /usr/bin/pmanh
else
	## For 'root' user
	
	cp -r ./../pacman-helper /usr/lib
	ln -s /usr/lib/pacman-helper/pmanh /usr/bin/pmanh
fi

## App has been installed
pmanh -v
