#!/bin/bash

## PMan
## Pacman package handler

VERSION='v0.1.0'

## Version
if [ $1 = '-v' ]; then
	echo "Pacman Helper"
	echo "Version: $VERSION"
	exit 0
fi

### User as root?
if [ $EUID -ne 0 ]; then
	echo $'Not running as ROOT\n'
else
	echo $'Running as ROOT\n'
fi

### Options
PS3="Enter a pacman option: "
OP=(
				"Update & Upgrade" 
				"Install an application" 
				"Uninstall an application"
				"Uninstall application and dependecies"
				"Search for an application"
				"List orphan dependencies"
				"Quit"
)

select OPT in "${OP[@]}"
do
				case $OPT in
								"Update & Upgrade")
												echo "Command => [sudo pacman -Suy]"
												
												if [ $EUID -ne 0 ]; then
													sudo pacman -Suy
												else
													pacman -Suy
												fi

												break
												;;

								"Install an application")
												echo "Enter the app name to install: "
												read appname

												echo "Command => [sudo pacman -S $appname]"

												if [ $EUID -ne 0 ]; then
													sudo pacman -S $appname
												else
													pacman -S $appname
												fi

												break
												;;

								"Uninstall an application")
												echo "Enter the app name to uninstall: "
												read appname

												echo "Command => [sudo pacman -R $appname]"

												if [ $EUID -ne 0 ]; then
													sudo pacman -R $appname
												else
													pacman -R $appname
												fi
												
												break
												;;

								"Uninstall application and dependecies")
												echo "Enter the app name to uninstall: "
												read appname
												
												echo "Command => [sudo pacman -Rs $appname]"

												if [ $EUID -ne 0 ]; then
													sudo pacman -Rs $appname
												else
													pacman -Rs $appname
												fi

												break;
												;;

								"Search for an application")
												echo "Enter a name to search for: "
												read searchname
											
												echo "Command => [sudo pacman -Ss $searchname]"

												pacman -Ss $searchname
												break
												;;

								"List orphan dependencies")
												echo "Command => [sudo pacman -Qdt]"

												pacman -Qdt
												break
												;;

								"Quit")
												break
												;;

								*) echo "Invalid $REPLY";;
				esac
done
